### 201 {}

POST http://localhost:5000/api/users
Content-Type: application/json

{
  "firstName":"Test",
  "lastName":"Testovych",
  "email":"t@t.com",
  "birthday":"2000-01-01",
  "gender": "male",
  "isMerried":true,
  "workExperience": 2
}
